<% require Rails.root.join("config/configs/boot_config") %>
<% BootConfig.load_from_env! %>
development:
  adapter: async

test:
  adapter: test

production:
  adapter: redis
  url: <%= BootConfig.config.redis.url %>
  channel_prefix: wildwaters_production
