<% database_config = BootConfig.config.database %>
default: &default
  adapter: postgis
  encoding: unicode
  seeds: false
  pool: <%= database_config.pool %>
  max_connections: <%= database_config.max_connections %>
  host: <%= database_config.host %>
  port: <%= database_config.port %>
  username: <%= database_config.username %>
  password: <%= database_config.password %>

development:
  primary: &primary
    <<: *default
    database: <%= database_config.name %>
  queue: &queue
    <<: *primary
    database: <%= database_config.queue_name %>
    migrations_paths: db/queue_migrate

test:
  primary: *primary
  queue: *queue

production:
  primary: *primary
  cache:
    <<: *primary
    database: <%= database_config.cache_name %>
    migrations_paths: db/cache_migrate
  queue: *queue
  cable:
    <<: *primary
    database: <%= database_config.cable_name %>
    migrations_paths: db/cable_migrate
