<% require Rails.root.join("config/configs/boot_config") %>
<% BootConfig.load_from_env! %>
<% database_config = BootConfig.config.database %>
default: &default
  adapter: postgis
  encoding: unicode
  seeds: false
  pool: <%= database_config.pool %>
  max_connections: <%= database_config.max_connections %>
  host: <%= database_config.host %>
  port: <%= database_config.port %>
  username: <%= database_config.username %>
  password: <%= database_config.password %>

development:
  primary: &primary_development
    <<: *default
    database: <%= database_config.development.primary_name %>
  queue:
    <<: *primary_development
    database: <%= database_config.development.queue_name %>
    migrations_paths: db/queue_migrate

test:
  primary: &primary_test
    <<: *default
    database: <%= database_config.test.primary_name %>
  queue:
    <<: *primary_test
    database: <%= database_config.test.queue_name %>
    migrations_paths: db/queue_migrate

production:
  primary: &primary_production
    <<: *default
    host: <%= database_config.production.host %>
    database: <%= database_config.production.primary_name %>
    username: <%= database_config.production.username %>
    password: <%= database_config.production_password %>
  cache:
    <<: *primary_production
    database: <%= database_config.production.cache_name %>
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: <%= database_config.production.queue_name %>
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: <%= database_config.production.cable_name %>
    migrations_paths: db/cable_migrate
