SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: citext; Type: EXTENSION; Schema: -; Owner: -
--

CREATE EXTENSION IF NOT EXISTS citext WITH SCHEMA public;


--
-- Name: EXTENSION citext; Type: COMMENT; Schema: -; Owner: -
--

COMMENT ON EXTENSION citext IS 'data type for case-insensitive character strings';


--
-- Name: pg_trgm; Type: EXTENSION; Schema: -; Owner: -
--

CREATE EXTENSION IF NOT EXISTS pg_trgm WITH SCHEMA public;


--
-- Name: EXTENSION pg_trgm; Type: COMMENT; Schema: -; Owner: -
--

COMMENT ON EXTENSION pg_trgm IS 'text similarity measurement and index searching based on trigrams';


--
-- Name: postgis; Type: EXTENSION; Schema: -; Owner: -
--

CREATE EXTENSION IF NOT EXISTS postgis WITH SCHEMA public;


--
-- Name: EXTENSION postgis; Type: COMMENT; Schema: -; Owner: -
--

COMMENT ON EXTENSION postgis IS 'PostGIS geometry and geography spatial types and functions';


SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: ar_internal_metadata; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.ar_internal_metadata (
    key character varying NOT NULL,
    value character varying,
    created_at timestamp(6) without time zone NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL
);


--
-- Name: import_record_snapshots; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.import_record_snapshots (
    id bigint NOT NULL,
    import_source_record_id bigint NOT NULL,
    import_run_id bigint NOT NULL,
    checksum text NOT NULL,
    payload jsonb,
    artifact_path text,
    captured_at timestamp with time zone NOT NULL,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);


--
-- Name: import_record_snapshots_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.import_record_snapshots ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.import_record_snapshots_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: import_region_source_links; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.import_region_source_links (
    id bigint CONSTRAINT region_source_links_id_not_null NOT NULL,
    region_id uuid CONSTRAINT region_source_links_region_id_not_null NOT NULL,
    import_source_record_id bigint CONSTRAINT region_source_links_import_source_record_id_not_null NOT NULL,
    match_strategy text CONSTRAINT region_source_links_match_strategy_not_null NOT NULL,
    confidence numeric(5,4) CONSTRAINT region_source_links_confidence_not_null NOT NULL,
    locked boolean DEFAULT false CONSTRAINT region_source_links_locked_not_null NOT NULL,
    primary_identity boolean DEFAULT false CONSTRAINT region_source_links_primary_identity_not_null NOT NULL,
    matched_at timestamp with time zone CONSTRAINT region_source_links_matched_at_not_null NOT NULL,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP CONSTRAINT region_source_links_created_at_not_null NOT NULL,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP CONSTRAINT region_source_links_updated_at_not_null NOT NULL,
    CONSTRAINT import_region_source_links_confidence_check CHECK (((confidence >= (0)::numeric) AND (confidence <= (1)::numeric)))
);


--
-- Name: import_region_source_links_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.import_region_source_links ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.import_region_source_links_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: import_run_items; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.import_run_items (
    id bigint NOT NULL,
    import_run_id bigint NOT NULL,
    item_kind text NOT NULL,
    item_key text NOT NULL,
    status text NOT NULL,
    params jsonb DEFAULT '{}'::jsonb NOT NULL,
    artifact_paths jsonb DEFAULT '{}'::jsonb NOT NULL,
    stats jsonb DEFAULT '{}'::jsonb NOT NULL,
    attempts_count integer DEFAULT 0 NOT NULL,
    started_at timestamp with time zone,
    finished_at timestamp with time zone,
    error_class text,
    error_message text,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT import_run_items_status_check CHECK ((status = ANY (ARRAY['queued'::text, 'running'::text, 'succeeded'::text, 'failed'::text, 'cancelled'::text])))
);


--
-- Name: import_run_items_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.import_run_items ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.import_run_items_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: import_runs; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.import_runs (
    id bigint NOT NULL,
    import_source_id bigint NOT NULL,
    mode text NOT NULL,
    status text NOT NULL,
    started_at timestamp with time zone,
    finished_at timestamp with time zone,
    cursor_in text,
    cursor_out text,
    stats jsonb DEFAULT '{}'::jsonb NOT NULL,
    error_class text,
    error_message text,
    initiated_by text DEFAULT 'system'::text NOT NULL,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    params jsonb DEFAULT '{}'::jsonb NOT NULL,
    CONSTRAINT import_runs_mode_check CHECK ((mode = ANY (ARRAY['full'::text, 'incremental'::text, 'backfill'::text, 'replay'::text]))),
    CONSTRAINT import_runs_status_check CHECK ((status = ANY (ARRAY['queued'::text, 'running'::text, 'succeeded'::text, 'failed'::text, 'partially_failed'::text, 'cancelled'::text])))
);


--
-- Name: import_runs_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.import_runs ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.import_runs_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: import_source_records; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.import_source_records (
    id bigint NOT NULL,
    import_source_id bigint NOT NULL,
    record_kind text NOT NULL,
    external_uid text NOT NULL,
    external_url text,
    status text NOT NULL,
    checksum text NOT NULL,
    raw_payload jsonb,
    normalized_payload jsonb DEFAULT '{}'::jsonb NOT NULL,
    first_seen_at timestamp with time zone NOT NULL,
    last_seen_at timestamp with time zone NOT NULL,
    last_changed_at timestamp with time zone,
    last_import_run_id bigint,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT import_source_records_status_check CHECK ((status = ANY (ARRAY['pending'::text, 'matched'::text, 'unresolved'::text, 'failed'::text, 'missing_upstream'::text])))
);


--
-- Name: import_source_records_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.import_source_records ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.import_source_records_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: import_sources; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.import_sources (
    id bigint NOT NULL,
    key text NOT NULL,
    target_kind text NOT NULL,
    source_role text NOT NULL,
    fetch_mode text NOT NULL,
    enabled boolean DEFAULT true NOT NULL,
    license_key text NOT NULL,
    license_url text,
    attribution_text text,
    display_policy text NOT NULL,
    compliance_notes text,
    config jsonb DEFAULT '{}'::jsonb NOT NULL,
    last_successful_run_at timestamp with time zone,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT import_sources_display_policy_check CHECK ((display_policy = ANY (ARRAY['public_display_allowed'::text, 'derived_only'::text, 'internal_only'::text]))),
    CONSTRAINT import_sources_fetch_mode_check CHECK ((fetch_mode = ANY (ARRAY['dump'::text, 'api'::text, 'scrape'::text, 'manual_file'::text]))),
    CONSTRAINT import_sources_source_role_check CHECK ((source_role = ANY (ARRAY['canonical_identity'::text, 'name_enrichment'::text, 'geometry_enrichment'::text, 'analysis_only'::text])))
);


--
-- Name: import_sources_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.import_sources ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.import_sources_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: region_closures; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.region_closures (
    ancestor_id uuid NOT NULL,
    descendant_id uuid NOT NULL,
    depth integer NOT NULL,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);


--
-- Name: region_names; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.region_names (
    id uuid DEFAULT uuidv7() NOT NULL,
    region_id uuid NOT NULL,
    import_source_record_id bigint,
    language_code text,
    name text NOT NULL,
    normalized_name text NOT NULL,
    name_role text NOT NULL,
    preferred boolean DEFAULT false NOT NULL,
    searchable boolean DEFAULT true NOT NULL,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT region_names_name_role_check CHECK ((name_role = ANY (ARRAY['primary'::text, 'official'::text, 'preferred'::text, 'native'::text, 'alias'::text, 'ascii'::text])))
);


--
-- Name: regions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.regions (
    id uuid DEFAULT uuidv7() NOT NULL,
    public_id text NOT NULL,
    parent_id uuid,
    name text NOT NULL,
    slug text NOT NULL,
    region_kind text CONSTRAINT regions_region_type_not_null NOT NULL,
    summary text,
    description text,
    status text DEFAULT 'active'::text NOT NULL,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    country_code text,
    center public.geography(Point,4326)
);


--
-- Name: schema_migrations; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.schema_migrations (
    version character varying NOT NULL
);


--
-- Name: sessions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.sessions (
    id uuid DEFAULT uuidv7() NOT NULL,
    user_id uuid NOT NULL,
    user_identity_id uuid NOT NULL,
    authentication_method text NOT NULL,
    ip_address inet,
    user_agent text,
    last_seen_at timestamp with time zone NOT NULL,
    expires_at timestamp with time zone NOT NULL,
    revoked_at timestamp with time zone,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    token_digest text NOT NULL
);


--
-- Name: spots; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.spots (
    id uuid DEFAULT uuidv7() NOT NULL,
    public_id text NOT NULL,
    region_id uuid NOT NULL,
    spot_type text NOT NULL,
    name text NOT NULL,
    slug text NOT NULL,
    summary text,
    description text,
    status text DEFAULT 'draft'::text NOT NULL,
    published_at timestamp with time zone,
    location public.geography(Point,4326) NOT NULL,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);


--
-- Name: user_identities; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.user_identities (
    id uuid DEFAULT uuidv7() NOT NULL,
    user_id uuid NOT NULL,
    provider text NOT NULL,
    provider_uid text,
    email public.citext,
    email_verified boolean DEFAULT false NOT NULL,
    password_digest text,
    metadata jsonb DEFAULT '{}'::jsonb NOT NULL,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    password_reset_token_digest text,
    password_reset_sent_at timestamp with time zone
);


--
-- Name: users; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.users (
    id uuid DEFAULT uuidv7() NOT NULL,
    primary_email public.citext NOT NULL,
    primary_email_verified_at timestamp with time zone,
    role text DEFAULT 'member'::text NOT NULL,
    status text DEFAULT 'active'::text NOT NULL,
    display_name text,
    locale text DEFAULT 'en'::text NOT NULL,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);


--
-- Name: waterfalls; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.waterfalls (
    id uuid DEFAULT uuidv7() NOT NULL,
    spot_id uuid NOT NULL,
    height_meters numeric(6,2),
    plunge_pool boolean,
    flow_seasonality text,
    approach_difficulty text,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);


--
-- Name: ar_internal_metadata ar_internal_metadata_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.ar_internal_metadata
    ADD CONSTRAINT ar_internal_metadata_pkey PRIMARY KEY (key);


--
-- Name: import_record_snapshots import_record_snapshots_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.import_record_snapshots
    ADD CONSTRAINT import_record_snapshots_pkey PRIMARY KEY (id);


--
-- Name: import_region_source_links import_region_source_links_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.import_region_source_links
    ADD CONSTRAINT import_region_source_links_pkey PRIMARY KEY (id);


--
-- Name: import_run_items import_run_items_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.import_run_items
    ADD CONSTRAINT import_run_items_pkey PRIMARY KEY (id);


--
-- Name: import_runs import_runs_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.import_runs
    ADD CONSTRAINT import_runs_pkey PRIMARY KEY (id);


--
-- Name: import_source_records import_source_records_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.import_source_records
    ADD CONSTRAINT import_source_records_pkey PRIMARY KEY (id);


--
-- Name: import_sources import_sources_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.import_sources
    ADD CONSTRAINT import_sources_pkey PRIMARY KEY (id);


--
-- Name: region_closures region_closures_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.region_closures
    ADD CONSTRAINT region_closures_pkey PRIMARY KEY (ancestor_id, descendant_id);


--
-- Name: region_names region_names_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.region_names
    ADD CONSTRAINT region_names_pkey PRIMARY KEY (id);


--
-- Name: regions regions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.regions
    ADD CONSTRAINT regions_pkey PRIMARY KEY (id);


--
-- Name: schema_migrations schema_migrations_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.schema_migrations
    ADD CONSTRAINT schema_migrations_pkey PRIMARY KEY (version);


--
-- Name: sessions sessions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sessions
    ADD CONSTRAINT sessions_pkey PRIMARY KEY (id);


--
-- Name: spots spots_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.spots
    ADD CONSTRAINT spots_pkey PRIMARY KEY (id);


--
-- Name: user_identities user_identities_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_identities
    ADD CONSTRAINT user_identities_pkey PRIMARY KEY (id);


--
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);


--
-- Name: waterfalls waterfalls_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.waterfalls
    ADD CONSTRAINT waterfalls_pkey PRIMARY KEY (id);


--
-- Name: index_import_record_snapshots_on_import_run_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX index_import_record_snapshots_on_import_run_id ON public.import_record_snapshots USING btree (import_run_id);


--
-- Name: index_import_record_snapshots_on_import_source_record_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX index_import_record_snapshots_on_import_source_record_id ON public.import_record_snapshots USING btree (import_source_record_id);


--
-- Name: index_import_region_source_links_on_import_source_record_id; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX index_import_region_source_links_on_import_source_record_id ON public.import_region_source_links USING btree (import_source_record_id);


--
-- Name: index_import_region_source_links_on_region_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX index_import_region_source_links_on_region_id ON public.import_region_source_links USING btree (region_id);


--
-- Name: index_import_region_source_links_on_region_id_primary_identity; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX index_import_region_source_links_on_region_id_primary_identity ON public.import_region_source_links USING btree (region_id) WHERE (primary_identity = true);


--
-- Name: index_import_run_items_on_import_run_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX index_import_run_items_on_import_run_id ON public.import_run_items USING btree (import_run_id);


--
-- Name: index_import_run_items_on_run_kind_and_key; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX index_import_run_items_on_run_kind_and_key ON public.import_run_items USING btree (import_run_id, item_kind, item_key);


--
-- Name: index_import_run_items_on_status; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX index_import_run_items_on_status ON public.import_run_items USING btree (status);


--
-- Name: index_import_runs_on_import_source_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX index_import_runs_on_import_source_id ON public.import_runs USING btree (import_source_id);


--
-- Name: index_import_runs_on_import_source_id_active; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX index_import_runs_on_import_source_id_active ON public.import_runs USING btree (import_source_id) WHERE (status = ANY (ARRAY['queued'::text, 'running'::text]));


--
-- Name: index_import_source_records_on_last_import_run_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX index_import_source_records_on_last_import_run_id ON public.import_source_records USING btree (last_import_run_id);


--
-- Name: index_import_source_records_on_source_kind_and_external_uid; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX index_import_source_records_on_source_kind_and_external_uid ON public.import_source_records USING btree (import_source_id, record_kind, external_uid);


--
-- Name: index_import_sources_on_key; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX index_import_sources_on_key ON public.import_sources USING btree (key);


--
-- Name: index_import_sources_on_target_kind; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX index_import_sources_on_target_kind ON public.import_sources USING btree (target_kind);


--
-- Name: index_region_closures_on_ancestor_id_and_depth; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX index_region_closures_on_ancestor_id_and_depth ON public.region_closures USING btree (ancestor_id, depth);


--
-- Name: index_region_closures_on_descendant_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX index_region_closures_on_descendant_id ON public.region_closures USING btree (descendant_id);


--
-- Name: index_region_names_on_identity; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX index_region_names_on_identity ON public.region_names USING btree (region_id, COALESCE(language_code, ''::text), normalized_name, name_role);


--
-- Name: index_region_names_on_import_source_record_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX index_region_names_on_import_source_record_id ON public.region_names USING btree (import_source_record_id);


--
-- Name: index_region_names_on_language_code; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX index_region_names_on_language_code ON public.region_names USING btree (language_code);


--
-- Name: index_region_names_on_name_trgm; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX index_region_names_on_name_trgm ON public.region_names USING gin (name public.gin_trgm_ops);


--
-- Name: index_region_names_on_normalized_name_trgm; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX index_region_names_on_normalized_name_trgm ON public.region_names USING gin (normalized_name public.gin_trgm_ops);


--
-- Name: index_region_names_on_region_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX index_region_names_on_region_id ON public.region_names USING btree (region_id);


--
-- Name: index_regions_on_country_code; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX index_regions_on_country_code ON public.regions USING btree (country_code);


--
-- Name: index_regions_on_parent_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX index_regions_on_parent_id ON public.regions USING btree (parent_id);


--
-- Name: index_regions_on_parent_id_and_slug; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX index_regions_on_parent_id_and_slug ON public.regions USING btree (parent_id, slug) WHERE (parent_id IS NOT NULL);


--
-- Name: index_regions_on_public_id; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX index_regions_on_public_id ON public.regions USING btree (public_id);


--
-- Name: index_regions_on_slug_where_parent_id_is_null; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX index_regions_on_slug_where_parent_id_is_null ON public.regions USING btree (slug) WHERE (parent_id IS NULL);


--
-- Name: index_regions_on_status; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX index_regions_on_status ON public.regions USING btree (status);


--
-- Name: index_sessions_on_expires_at; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX index_sessions_on_expires_at ON public.sessions USING btree (expires_at);


--
-- Name: index_sessions_on_revoked_at; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX index_sessions_on_revoked_at ON public.sessions USING btree (revoked_at);


--
-- Name: index_sessions_on_token_digest; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX index_sessions_on_token_digest ON public.sessions USING btree (token_digest);


--
-- Name: index_sessions_on_user_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX index_sessions_on_user_id ON public.sessions USING btree (user_id);


--
-- Name: index_sessions_on_user_identity_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX index_sessions_on_user_identity_id ON public.sessions USING btree (user_identity_id);


--
-- Name: index_spots_on_location; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX index_spots_on_location ON public.spots USING gist (location);


--
-- Name: index_spots_on_public_id; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX index_spots_on_public_id ON public.spots USING btree (public_id);


--
-- Name: index_spots_on_region_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX index_spots_on_region_id ON public.spots USING btree (region_id);


--
-- Name: index_spots_on_region_id_and_slug; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX index_spots_on_region_id_and_slug ON public.spots USING btree (region_id, slug);


--
-- Name: index_spots_on_spot_type; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX index_spots_on_spot_type ON public.spots USING btree (spot_type);


--
-- Name: index_spots_on_status; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX index_spots_on_status ON public.spots USING btree (status);


--
-- Name: index_user_identities_on_password_reset_token_digest; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX index_user_identities_on_password_reset_token_digest ON public.user_identities USING btree (password_reset_token_digest) WHERE (password_reset_token_digest IS NOT NULL);


--
-- Name: index_user_identities_on_provider_and_provider_uid; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX index_user_identities_on_provider_and_provider_uid ON public.user_identities USING btree (provider, provider_uid) WHERE (provider_uid IS NOT NULL);


--
-- Name: index_user_identities_on_user_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX index_user_identities_on_user_id ON public.user_identities USING btree (user_id);


--
-- Name: index_user_identities_on_user_id_and_provider_for_password; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX index_user_identities_on_user_id_and_provider_for_password ON public.user_identities USING btree (user_id, provider) WHERE (provider = 'password'::text);


--
-- Name: index_users_on_primary_email; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX index_users_on_primary_email ON public.users USING btree (primary_email);


--
-- Name: index_waterfalls_on_spot_id; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX index_waterfalls_on_spot_id ON public.waterfalls USING btree (spot_id);


--
-- Name: import_record_snapshots import_record_snapshots_import_run_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.import_record_snapshots
    ADD CONSTRAINT import_record_snapshots_import_run_id_fkey FOREIGN KEY (import_run_id) REFERENCES public.import_runs(id);


--
-- Name: import_record_snapshots import_record_snapshots_import_source_record_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.import_record_snapshots
    ADD CONSTRAINT import_record_snapshots_import_source_record_id_fkey FOREIGN KEY (import_source_record_id) REFERENCES public.import_source_records(id) ON DELETE CASCADE;


--
-- Name: import_region_source_links import_region_source_links_import_source_record_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.import_region_source_links
    ADD CONSTRAINT import_region_source_links_import_source_record_id_fkey FOREIGN KEY (import_source_record_id) REFERENCES public.import_source_records(id) ON DELETE CASCADE;


--
-- Name: import_region_source_links import_region_source_links_region_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.import_region_source_links
    ADD CONSTRAINT import_region_source_links_region_id_fkey FOREIGN KEY (region_id) REFERENCES public.regions(id) ON DELETE CASCADE;


--
-- Name: import_run_items import_run_items_import_run_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.import_run_items
    ADD CONSTRAINT import_run_items_import_run_id_fkey FOREIGN KEY (import_run_id) REFERENCES public.import_runs(id);


--
-- Name: import_runs import_runs_import_source_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.import_runs
    ADD CONSTRAINT import_runs_import_source_id_fkey FOREIGN KEY (import_source_id) REFERENCES public.import_sources(id);


--
-- Name: import_source_records import_source_records_import_source_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.import_source_records
    ADD CONSTRAINT import_source_records_import_source_id_fkey FOREIGN KEY (import_source_id) REFERENCES public.import_sources(id);


--
-- Name: import_source_records import_source_records_last_import_run_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.import_source_records
    ADD CONSTRAINT import_source_records_last_import_run_id_fkey FOREIGN KEY (last_import_run_id) REFERENCES public.import_runs(id);


--
-- Name: region_closures region_closures_ancestor_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.region_closures
    ADD CONSTRAINT region_closures_ancestor_id_fkey FOREIGN KEY (ancestor_id) REFERENCES public.regions(id) ON DELETE CASCADE;


--
-- Name: region_closures region_closures_descendant_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.region_closures
    ADD CONSTRAINT region_closures_descendant_id_fkey FOREIGN KEY (descendant_id) REFERENCES public.regions(id) ON DELETE CASCADE;


--
-- Name: region_names region_names_import_source_record_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.region_names
    ADD CONSTRAINT region_names_import_source_record_id_fkey FOREIGN KEY (import_source_record_id) REFERENCES public.import_source_records(id) ON DELETE SET NULL;


--
-- Name: region_names region_names_region_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.region_names
    ADD CONSTRAINT region_names_region_id_fkey FOREIGN KEY (region_id) REFERENCES public.regions(id) ON DELETE CASCADE;


--
-- Name: regions regions_parent_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.regions
    ADD CONSTRAINT regions_parent_id_fkey FOREIGN KEY (parent_id) REFERENCES public.regions(id) ON DELETE SET NULL;


--
-- Name: sessions sessions_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sessions
    ADD CONSTRAINT sessions_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE;


--
-- Name: sessions sessions_user_identity_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sessions
    ADD CONSTRAINT sessions_user_identity_id_fkey FOREIGN KEY (user_identity_id) REFERENCES public.user_identities(id) ON DELETE CASCADE;


--
-- Name: spots spots_region_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.spots
    ADD CONSTRAINT spots_region_id_fkey FOREIGN KEY (region_id) REFERENCES public.regions(id) ON DELETE RESTRICT;


--
-- Name: user_identities user_identities_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_identities
    ADD CONSTRAINT user_identities_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE;


--
-- Name: waterfalls waterfalls_spot_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.waterfalls
    ADD CONSTRAINT waterfalls_spot_id_fkey FOREIGN KEY (spot_id) REFERENCES public.spots(id) ON DELETE CASCADE;


--
-- PostgreSQL database dump complete
--

SET search_path TO "$user", public;

INSERT INTO "schema_migrations" (version) VALUES
('20260428130000'),
('20260424120000'),
('20260331103000'),
('20260331102000'),
('20260331101000'),
('20260331100000'),
('20260315222004'),
('20260315213827'),
('20260314234833'),
('20260314143000'),
('20260314142000'),
('20260314093000');

