class AddImportRunItemsForGeonamesOrchestration < ActiveRecord::Migration[8.1]
  def up
    execute <<~SQL
      ALTER TABLE import_runs
        ADD COLUMN params jsonb NOT NULL DEFAULT '{}'::jsonb;
    SQL

    execute <<~SQL
      ALTER TABLE import_runs
        DROP CONSTRAINT import_runs_status_check;
    SQL

    execute <<~SQL
      ALTER TABLE import_runs
        ADD CONSTRAINT import_runs_status_check
        CHECK (status IN ('queued', 'running', 'succeeded', 'failed', 'partially_failed', 'cancelled'));
    SQL

    execute <<~SQL
      CREATE TABLE import_run_items (
        id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        import_run_id bigint NOT NULL REFERENCES import_runs(id),
        item_kind text NOT NULL,
        item_key text NOT NULL,
        status text NOT NULL,
        country_code text,
        params jsonb NOT NULL DEFAULT '{}'::jsonb,
        artifact_paths jsonb NOT NULL DEFAULT '{}'::jsonb,
        stats jsonb NOT NULL DEFAULT '{}'::jsonb,
        attempts_count integer NOT NULL DEFAULT 0,
        started_at timestamptz,
        finished_at timestamptz,
        error_class text,
        error_message text,
        created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
        updated_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
        CONSTRAINT import_run_items_status_check
          CHECK (status IN ('queued', 'running', 'succeeded', 'failed', 'cancelled'))
      );
    SQL

    execute <<~SQL
      CREATE INDEX index_import_run_items_on_import_run_id
        ON import_run_items (import_run_id);
    SQL

    execute <<~SQL
      CREATE INDEX index_import_run_items_on_status
        ON import_run_items (status);
    SQL

    execute <<~SQL
      CREATE UNIQUE INDEX index_import_run_items_on_run_kind_and_key
        ON import_run_items (import_run_id, item_kind, item_key);
    SQL
  end

  def down
    execute <<~SQL
      DROP TABLE IF EXISTS import_run_items;
    SQL

    execute <<~SQL
      ALTER TABLE import_runs
        DROP CONSTRAINT import_runs_status_check;
    SQL

    execute <<~SQL
      ALTER TABLE import_runs
        ADD CONSTRAINT import_runs_status_check
        CHECK (status IN ('queued', 'running', 'succeeded', 'failed', 'cancelled'));
    SQL

    execute <<~SQL
      ALTER TABLE import_runs
        DROP COLUMN params;
    SQL
  end
end
