class CreateRegionSourceLinks < ActiveRecord::Migration[8.1]
  def up
    execute <<~SQL
      CREATE TABLE region_source_links (
        id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        region_id uuid NOT NULL REFERENCES regions(id) ON DELETE CASCADE,
        import_source_record_id bigint NOT NULL REFERENCES import_source_records(id) ON DELETE CASCADE,
        match_strategy text NOT NULL,
        confidence numeric(5,4) NOT NULL,
        locked boolean NOT NULL DEFAULT FALSE,
        primary_identity boolean NOT NULL DEFAULT FALSE,
        matched_at timestamptz NOT NULL,
        created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
        updated_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
        CONSTRAINT region_source_links_confidence_check
          CHECK (confidence >= 0 AND confidence <= 1)
      );
    SQL

    execute <<~SQL
      CREATE UNIQUE INDEX index_region_source_links_on_import_source_record_id
        ON region_source_links (import_source_record_id);
    SQL

    execute <<~SQL
      CREATE INDEX index_region_source_links_on_region_id
        ON region_source_links (region_id);
    SQL

    execute <<~SQL
      CREATE UNIQUE INDEX index_region_source_links_on_region_id_primary_identity
        ON region_source_links (region_id)
        WHERE primary_identity = TRUE;
    SQL
  end

  def down
    execute <<~SQL
      DROP TABLE IF EXISTS region_source_links;
    SQL
  end
end
