class CreateImportFoundation < ActiveRecord::Migration[8.1]
  def up
    execute <<~SQL
      CREATE TABLE import_sources (
        id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        key text NOT NULL,
        target_kind text NOT NULL,
        source_role text NOT NULL,
        fetch_mode text NOT NULL,
        enabled boolean NOT NULL DEFAULT TRUE,
        license_key text NOT NULL,
        license_url text,
        attribution_text text,
        display_policy text NOT NULL,
        compliance_notes text,
        config jsonb NOT NULL DEFAULT '{}'::jsonb,
        last_successful_run_at timestamptz,
        created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
        updated_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
        CONSTRAINT import_sources_source_role_check
          CHECK (source_role IN ('canonical_identity', 'name_enrichment', 'geometry_enrichment', 'analysis_only')),
        CONSTRAINT import_sources_fetch_mode_check
          CHECK (fetch_mode IN ('dump', 'api', 'scrape', 'manual_file')),
        CONSTRAINT import_sources_display_policy_check
          CHECK (display_policy IN ('public_display_allowed', 'derived_only', 'internal_only'))
      );
    SQL

    execute <<~SQL
      CREATE UNIQUE INDEX index_import_sources_on_key ON import_sources (key);
    SQL

    execute <<~SQL
      CREATE INDEX index_import_sources_on_target_kind ON import_sources (target_kind);
    SQL

    execute <<~SQL
      CREATE TABLE import_runs (
        id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        import_source_id bigint NOT NULL REFERENCES import_sources(id),
        mode text NOT NULL,
        status text NOT NULL,
        started_at timestamptz,
        finished_at timestamptz,
        cursor_in text,
        cursor_out text,
        stats jsonb NOT NULL DEFAULT '{}'::jsonb,
        error_class text,
        error_message text,
        initiated_by text NOT NULL DEFAULT 'system',
        created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
        updated_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
        CONSTRAINT import_runs_mode_check
          CHECK (mode IN ('full', 'incremental', 'backfill', 'replay')),
        CONSTRAINT import_runs_status_check
          CHECK (status IN ('queued', 'running', 'succeeded', 'failed', 'cancelled'))
      );
    SQL

    execute <<~SQL
      CREATE INDEX index_import_runs_on_import_source_id ON import_runs (import_source_id);
    SQL

    execute <<~SQL
      CREATE UNIQUE INDEX index_import_runs_on_import_source_id_active
        ON import_runs (import_source_id)
        WHERE status IN ('queued', 'running');
    SQL

    execute <<~SQL
      CREATE TABLE import_source_records (
        id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        import_source_id bigint NOT NULL REFERENCES import_sources(id),
        record_kind text NOT NULL,
        external_uid text NOT NULL,
        external_url text,
        status text NOT NULL,
        checksum text NOT NULL,
        raw_payload jsonb,
        normalized_payload jsonb NOT NULL DEFAULT '{}'::jsonb,
        first_seen_at timestamptz NOT NULL,
        last_seen_at timestamptz NOT NULL,
        last_changed_at timestamptz,
        last_import_run_id bigint REFERENCES import_runs(id),
        created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
        updated_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
        CONSTRAINT import_source_records_status_check
          CHECK (status IN ('pending', 'matched', 'unresolved', 'failed', 'missing_upstream'))
      );
    SQL

    execute <<~SQL
      CREATE UNIQUE INDEX index_import_source_records_on_source_kind_and_external_uid
        ON import_source_records (import_source_id, record_kind, external_uid);
    SQL

    execute <<~SQL
      CREATE INDEX index_import_source_records_on_last_import_run_id
        ON import_source_records (last_import_run_id);
    SQL

    execute <<~SQL
      CREATE TABLE import_record_snapshots (
        id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        import_source_record_id bigint NOT NULL REFERENCES import_source_records(id) ON DELETE CASCADE,
        import_run_id bigint NOT NULL REFERENCES import_runs(id),
        checksum text NOT NULL,
        payload jsonb,
        artifact_path text,
        captured_at timestamptz NOT NULL,
        created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
        updated_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP
      );
    SQL

    execute <<~SQL
      CREATE INDEX index_import_record_snapshots_on_import_source_record_id
        ON import_record_snapshots (import_source_record_id);
    SQL

    execute <<~SQL
      CREATE INDEX index_import_record_snapshots_on_import_run_id
        ON import_record_snapshots (import_run_id);
    SQL
  end

  def down
    execute <<~SQL
      DROP TABLE IF EXISTS import_record_snapshots;
    SQL

    execute <<~SQL
      DROP TABLE IF EXISTS import_source_records;
    SQL

    execute <<~SQL
      DROP TABLE IF EXISTS import_runs;
    SQL

    execute <<~SQL
      DROP TABLE IF EXISTS import_sources;
    SQL
  end
end
